/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pmath_Expr */

#ifndef _Included_pmath_Expr
#define _Included_pmath_Expr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pmath_Expr
 * Method:    execute
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_pmath_Expr_execute
  (JNIEnv *, jclass, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
