/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pmath_Core */

#ifndef _Included_pmath_Core
#define _Included_pmath_Core
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pmath_Core
 * Method:    execute
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_pmath_Core_execute
  (JNIEnv *, jclass, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
